### ISSUE TITLE
Code generation for OpenAPI v3 doesn't seem to work at all

### ISSUE THREAD

**Issue by matyat** [googleapis/gnostic-go-generator#15]
From the examples:
```
$ gnostic bookstore.json --go-generator-out=bookstore
Errors reading bookstore.json
Plugin error: [types.go:31:12: expected ';', found '/' (and 10 more errors)]
Plugin error: [types.go:31:12: expected ';', found '/' (and 10 more errors)]
```

Doesn't seem to work for any other openapi v3 definitions I have on hand.

**Comment by LorenzHW** [comment]
Ohhh! I think that is my fault. Totally forgot that I have an open ToDo here. Sorry!

@noahdietz please assign this to me. I will fix this ASAP.

**Comment by noahdietz** [comment]
Thanks @LorenzHW !
